---
# file defaults/config_agent.yml

- name: Uninstall buiagent pip2 packages when using pip3 as pip executable
  pip:
    name: "{{ burp_agent_pip_burpui }}"
    state: absent
    executable: "pip2"
  retries: 3
  delay: 2
  when: python_pip_executable == "pip3" and pip2_executable_stat.stat.exists

- name: install buiagent pip packages
  pip:
    name: "{{ burp_agent_pip_present }}"
    state: present
    executable: "{{ python_pip_root_path }}/{{ python_pip_executable }}"
    extra_args: --ignore-installed six
  retries: 3
  delay: 2

- name: Install buiagent pip
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version }}"
    executable: "{{ python_pip_root_path }}/{{ python_pip_executable }}"
  with_items: "{{ burpui_pip_packages }}"
  retries: 3
  delay: 2
  notify:
    - restart bui-agent
    - restart bui-agent systemd

- name: configure buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.cfg.j2", dest: "/etc/burp/buiagent.cfg" }
  notify:
    - restart bui-agent
    - restart bui-agent systemd
