---
# file defaults/config_agent.yml

- name: install buiagent pip3 packages
  pip:
    name: "{{ burp_agent_pip_present }}"
    state: present
    executable: "{{ python3_pip }}"
    extra_args: --ignore-installed six
  retries: 3
  delay: 2

- name: Install buiagent pip3
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version }}"
    executable: "{{ python3_pip }}"
  with_items: "{{ burpui_pip_packages }}"
  retries: 3
  delay: 2
  notify:
    - restart bui-agent
    - restart bui-agent systemd

- name: configure buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.cfg.j2", dest: "/etc/burp/buiagent.cfg" }
  notify:
    - restart bui-agent
    - restart bui-agent systemd
