---
# file defaults/config_agent.yml

# https://github.com/ansible/ansible/issues/28952
- name: update pip to avoid idempotence issues
  pip:
    name: "pip>=22.2.2"
    state: present
    executable: "{{ python3_pip }}"
  retries: 3
  delay: 2

# for some pip packages we need to use requirements file to fix idempotence issues
- name: config_agent | copy pip_requirements_burp_agent_pip_present file
  template:
    src: "pip_requirements_burp_agent_pip_present.j2"
    dest: "/tmp/pip_requirements_burp_agent_pip_present.txt"

# use package name==version or name>=version to avoid
# issues with pip idempotence
- name: install buiagent pip3 packages
  pip:
    requirements: "/tmp/pip_requirements_burp_agent_pip_present.txt"
    state: present
    executable: "{{ python3_pip }}"
  retries: 3
  delay: 2

# use package name==version or name>=version to avoid
# issues with pip idempotence
- name: Install buiagent pip3
  pip:
    name: "{{ burpui_pip_package }}"
    state: present
    executable: "{{ python3_pip }}"
  retries: 3
  delay: 2
  notify:
    - restart bui-agent
    - restart bui-agent systemd

- name: configure buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.cfg.j2", dest: "/etc/burp/buiagent.cfg" }
  notify:
    - restart bui-agent
    - restart bui-agent systemd
