---
# tasks file for ansible_burpui_agent/

- include: multi_os.yml

- name: install buiagent packages
  package:
    name: "{{ burp_agent_packages| join(',') }}"
    state: present
  retries: 3
  delay: 2
  when: python_pip_executable != "pip3"

- name: install buiagent packages for pip3
  package:
    name: "{{ burp_agent_py3_packages| join(',') }}"
    state: present
  retries: 3
  delay: 2
  when: python_pip_executable == "pip3"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: stat to see if /usr/bin/pip2 exists
  stat:
    path: '/usr/bin/pip2'
  register: pip2_executable_stat

- name: stat to see if /usr/bin/pip3 exists
  stat:
    path: '/usr/bin/pip3'
  register: pip3_executable_stat

- name: set /usr/bin if /usr/bin/pip3 exists
  register:
    python_pip_root_path: "/usr/bin"
  when: pip3_executable_stat.stat.exists

- include: config_agent.yml

- include: supervisor.yml
  when: not bui_agent_systemd

- include: systemd.yml
  when: bui_agent_systemd
