---
# tasks file for ansible_burpui_agent/

- include: multi_os.yml

- name: install requirements for ansible pip
  package:
    name: ['python3-setuptools']
    state: present

- name: install buiagent packages for pip3
  package:
    name: "{{ burp_agent_py3_packages| join(',') }}"
    state: present
  retries: 3
  delay: 2

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_agent.yml

- include: supervisor.yml
  when: not bui_agent_systemd | bool

- include: systemd.yml
  when: bui_agent_systemd | bool
