---
# tasks file for ansible_burpui_agent/

- import_tasks: multi_os.yml

- name: install requirements for ansible pip
  package:
    name: ['python3-setuptools']
    state: present

- name: install buiagent packages for pip3
  package:
    name: "{{ burp_agent_py3_packages| join(',') }}"
    state: present
  retries: 3
  delay: 2

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: main | create virtualenv dir
  ansible.builtin.file:
    path: "{{ burpui_virtualenv }}"
    state: directory 
    owner: root
    group: root
    mode: '0755'

- import_tasks: config_agent.yml

- import_tasks: supervisor.yml
  when: not bui_agent_systemd | bool

- import_tasks: systemd.yml
  when: bui_agent_systemd | bool
