---
# file tasks/redhat.yml

- name: redhat | install EPEL release package for Centos
  yum:
    name: "epel-release"
    state: present
  retries: 3
  delay: 2
  when: ansible_distribution == 'CentOS'
