---
# file tasks/redhat.yml

- name: redhat | install EPEL release package for RHEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  retries: 2
  delay: 2
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: redhat | install EPEL release package for Centos
  yum:
    name: "epel-release"
    state: present
  retries: 3
  delay: 2
  when: ansible_distribution == 'CentOS'

- name: redhat | set pip3 packages for redhat and centos
  set_fact:
    burp_agent_py3_packages:
      - python36
      - python36-devel
      - python36-pip
      - redhat-rpm-config
  when: ansible_distribution != "Fedora" and python_pip_executable == 'pip3'

- name: redhat | ensure pip3 command setup is done
  easy_install:
    name: pip
    state: latest
    executable: easy_install-3.6
  when: ansible_distribution != "Fedora" and python_pip_executable == 'pip3'
