---
# Setup systemd service
# Only used when not using supervisord

# burpui-agent
- name: systemd | configure systemd service for bui-agent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "systemd/bui-agent.service.j2",
        dest: "/etc/systemd/system/bui-agent.service" }
#  notify:
#    - systemd daemon-reload

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: systemd | enable bui-agent service
  systemd:
    daemon-reload: yes
    name: bui-agent
    state: started
    enabled: yes
  # For some reason ubuntu 22.04 failed in idempotence test here
  # Adding workaround for idempotence
  changed_when: false

- name: flush handlers
  meta: flush_handlers
